-- USER SQL
CREATE USER bookstore IDENTIFIED BY bookstore 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER bookstore QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "DBA" TO bookstore WITH ADMIN OPTION;
ALTER USER bookstore DEFAULT ROLE "DBA";

-- SYSTEM PRIVILEGES

