package bookstore.pbean;
// Generated 2009/09/17 12:35:57 by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TBook generated by hbm2java
 */
@Entity
@Table(name="T_BOOK"
    ,schema="BOOKSTORE"
)
public class TBook  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int id;
     private String isbn;
     private String title;
     private String author;
     private String publisher;
     private int price;
     private Set<TOrderDetail> tOrderDetails = new HashSet<>(0);

    public TBook() {
    }

	
    public TBook(int id, String isbn, String title, String author, String publisher, int price) {
        this.id = id;
        this.isbn = isbn;
        this.title = title;
        this.author = author;
        this.publisher = publisher;
        this.price = price;
    }
    public TBook(int id, String isbn, String title, String author, String publisher, int price, Set<TOrderDetail> tOrderDetails) {
       this.id = id;
       this.isbn = isbn;
       this.title = title;
       this.author = author;
       this.publisher = publisher;
       this.price = price;
       this.tOrderDetails = tOrderDetails;
    }
   
     @Id 

    
    @Column(name="ID", nullable=false, precision=22, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ISBN", unique=true, nullable=false, length=256)
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    
    @Column(name="TITLE", nullable=false, length=256)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="AUTHOR", nullable=false, length=256)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    
    @Column(name="PUBLISHER", nullable=false, length=256)
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    
    @Column(name="PRICE", nullable=false, precision=22, scale=0)
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="TBook")
    public Set<TOrderDetail> getTOrderDetails() {
        return this.tOrderDetails;
    }
    
    public void setTOrderDetails(Set<TOrderDetail> tOrderDetails) {
        this.tOrderDetails = tOrderDetails;
    }




}


