package bookstore.pbean;
// Generated 2009/09/17 12:35:57 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOrder generated by hbm2java
 */
@Entity
@Table(name="T_ORDER"
    ,schema="BOOKSTORE"
)
public class TOrder  implements java.io.Serializable {


     private int id;
     private TCustomer TCustomer;
     private Date orderday;
     private Set<TOrderDetail> TOrderDetails = new HashSet<TOrderDetail>(0);

    public TOrder() {
    }

	
    public TOrder(int id, TCustomer TCustomer, Date orderday) {
        this.id = id;
        this.TCustomer = TCustomer;
        this.orderday = orderday;
    }
    public TOrder(int id, TCustomer TCustomer, Date orderday, Set<TOrderDetail> TOrderDetails) {
       this.id = id;
       this.TCustomer = TCustomer;
       this.orderday = orderday;
       this.TOrderDetails = TOrderDetails;
    }
   
     @Id 

    
    @Column(name="ID", nullable=false, precision=22, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_ID_FK", nullable=false)
    public TCustomer getTCustomer() {
        return this.TCustomer;
    }
    
    public void setTCustomer(TCustomer TCustomer) {
        this.TCustomer = TCustomer;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ORDERDAY", nullable=false, length=11)
    public Date getOrderday() {
        return this.orderday;
    }
    
    public void setOrderday(Date orderday) {
        this.orderday = orderday;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="TOrder")
    public Set<TOrderDetail> getTOrderDetails() {
        return this.TOrderDetails;
    }
    
    public void setTOrderDetails(Set<TOrderDetail> TOrderDetails) {
        this.TOrderDetails = TOrderDetails;
    }




}


